deploymentMode: SingleBinary

loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  auth_enabled: false
  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h

singleBinary:
  replicas: 1
  resources:
    requests:
      cpu: 5m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 512Mi
  persistence:
    enabled: true
    storageClass: openebs-hostpath
    size: 2Gi

# Disable distributed components
read:
  replicas: 0
write:
  replicas: 0
backend:
  replicas: 0

gateway:
  replicas: 1
  affinity:
    podAntiAffinity: null

chunksCache:
  enabled: false
resultsCache:
  enabled: false

lokiCanary:
  enabled: false

test:
  enabled: false
