ingress:
  enabled: false

image:
  version: "v0.0.66"

serviceAccount:
  create: true

rbac:
  create: true
  extraClusterRoleBindings:
    - name: cluster-admin
      roleRef:
        name: cluster-admin
        external: true

service:
  port: 8080

httpRoute:
  enabled: true
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: traefik-gateway
      namespace: traefik
      sectionName: https
  hostnames:
    - kubernetes-mcp.home.zaramihnea.dev
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /

resources:
  requests:
    cpu: 5m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 256Mi
