defaultPodOptions:
  serviceAccountName: kubernetes-mcp

controllers:
  kubernetes-mcp:
    containers:
      app:
        image:
          repository: ghcr.io/manusa/kubernetes-mcp-server
          tag: latest
          pullPolicy: Always
        resources:
          requests:
            cpu: 5m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 256Mi

service:
  app:
    controller: kubernetes-mcp
    ports:
      http:
        port: 8080
