apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-httproutes
  namespace: keda
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: jellyfin
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: homarr
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: n8n
  to:
    - group: ""
      kind: Service
