grafana:
  url: http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local
  apiKeySecret:
    name: grafana-mcp-apikey
    key: api-key

image:
  tag: "1.1.0"

extraArgs:
  - --allowed-hosts=grafana-mcp.home.zaramihnea.dev

service:
  port: 8000

resources:
  requests:
    cpu: 5m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
