apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: scrypted
  namespace: scrypted
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
      sectionName: https
  hostnames:
    - scrypted.home.zaramihnea.dev
  rules:
    - backendRefs:
        - name: scrypted
          port: 11080
