apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scrypted-volume
  namespace: scrypted
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 2Gi
