apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: n8n
  namespace: n8n
spec:
  hosts:
    - n8n.home.zaramihnea.dev
  pathPrefixes:
    - /
  scaledownPeriod: 600
  replicas:
    min: 0
    max: 1
  targetPendingRequests: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: n8n
    service: n8n
    port: 5678
