apiVersion: http.keda.sh/v1beta1
kind: InterceptorRoute
metadata:
  name: n8n
  namespace: n8n
spec:
  rules:
    - hosts:
        - n8n.home.zaramihnea.dev
      paths:
        - value: /
  target:
    service: n8n
    port: 5678
  scalingMetric:
    concurrency:
      targetValue: 10
