apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: homarr
  namespace: homarr
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: homarr
  minReplicaCount: 0
  maxReplicaCount: 1
  cooldownPeriod: 600
  triggers:
    - type: external-push
      metadata:
        scalerAddress: keda-add-ons-http-external-scaler.keda:9090
        interceptorRoute: homarr
